### ISSUE TITLE
Tests fail: cannot import name 'Config' from 'pytest'

### ISSUE THREAD

**Issue by yurivict** [open-quantum-safe/liboqs#1534]
**Describe the bug**
```
[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/pytest.py", line 102, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 65, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 213, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 789, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 997, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 943, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 304, in load_module
    exec(co, mod.__dict__)
  File "/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py", line 6, in <module>
    from pytest import Config, Parser
ImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)
FAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests 
cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos
ninja: build stopped: subcommand failed.
*** Error code 1
```

**To Reproduce**
Regular build and test with the ```run_tests``` target.

**Environment (please complete the following information):**
 - OS: FreeBSD 13.2
 - Compiler version used clang-16
 - Build variables used n/a
 - liboqs version rev.914764c9

**Comment by baentsch** [comment]
Is this really an OQS problem? I don't see a single line of OQS (python/test) code involved in the trace above: Can you please point to that?

**Comment by yurivict** [comment]
Maybe pytest is unstable.
In my experience, pytest breaks a lot due to all sorts of problems on many projects.

**Comment by yurivict** [comment]
Yes, it is a pytest problem.

Sorry for the noise!

**Comment by Max8TaganskyGang** [comment]
how u solve it?
