### ISSUE TITLE
Add UOV sig alg

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#2028]
As per https://github.com/open-quantum-safe/oqs-provider/discussions/605#discussioncomment-11697369

**Comment by baentsch** [comment]
Thanks for letting us know @mkannwischer ! From the perspective of the overarching OQS goal of providing the widest possible selection of PQC algorithms, this would be great: Accordingly, added this to the next release milestone -- and I for one would rather push the release out than not include a new PQC alg.

**Comment by SWilson4** [comment]
This is exciting news! If you encounter any friction along the way, please let us know. (PRs to improve the integration process are also always welcome.)

**Comment by mkannwischer** [comment]
I have an update on the UOV integration.
I have sucessfully integreated 36 implementations of UOV into liboqs (12 parameter sets x {ref,neon,avx2}). CI (extended tests, full tests) is passing in my fork:
https://github.com/mkannwischer/liboqs/tree/uov
https://github.com/mkannwischer/liboqs/actions/runs/13654703210/job/38170961273

Still need to do some clean-up, but you can expect a PR tomorrow or the day after. I had to make some changes to the [pqov](https://github.com/pqov/pqov) and I want to merge those back to main first which requires review of my co-submitters.

A few minor points to feedback: 
1) Unfortunately, S is not the last letter in the alphabet. UOV comes after SPHINCS+ when ordering alphabetically. The liboqs import scripts assume that SPHINCS+ is the last scheme in an alphabetically orded list. I changed that in https://github.com/mkannwischer/liboqs/commit/22d5dd1699a7e3b78b3e08ca70c1ed4d6061f217
2) It is quite annoying that the copy_from_upstream.py scripts does not create files, but only updates them. I constantly got errors like this: 
```
Traceback (most recent call last):
  File "/Users/matthiaskannwischer/git/liboqs/scripts/copy_from_upstream/copy_from_upstream.py", line 831, in <module>
    copy_from_upstream()
  File "/Users/matthiaskannwischer/git/liboqs/scripts/copy_from_upstream/copy_from_upstream.py", line 700, in copy_from_upstream
    process_families(instructions, os.environ['LIBOQS_DIR'], True, True)
  File "/Users/matthiaskannwischer/git/liboqs/scripts/copy_from_upstream/copy_from_upstream.py", line 674, in process_families
    generator(
  File "/Users/matthiaskannwischer/git/liboqs/scripts/copy_from_upstream/copy_from_upstream.py", line 77, in generator
    contents = file_get_contents(os.path.join(os.environ['LIBOQS_DIR'], destination_file_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthiaskannwischer/git/liboqs/scripts/copy_from_upstream/copy_from_upstream.py", line 57, in file_get_contents
    with open(filename, mode='r', encoding=encoding) as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matthiaskannwischer/git/liboqs/src/sig/uov/sig_uov_ov_III.c'
```
If you then do a `touch /Users/matthiaskannwischer/git/liboqs/src/sig/uov/sig_uov_ov_III.c` and run the script again it works fine. Same for the `CMakeLists.txt`
3) Is there are way to import the "all" kat hashes from upstream as well? That would be convienent. I added those directly into the `kats.json`.
